# C sources
C_SOURCES +=  \
	$(wildcard Core/Src/stm32f10x_it.c) \

# CPP sources
CPP_SOURCES +=  \
	$(wildcard Core/Src/main.cpp) \

# ASM sources
ASM_SOURCES +=  \

# ASM sources
ASMM_SOURCES += \

# C/C++ includes
C_CPP_INCLUDES +=  \
	-I Core/Inc/ \
