# C sources
C_SOURCES +=  \
	$(wildcard Core/*.c) \

# CPP sources
CPP_SOURCES +=  \
	$(wildcard Core/*.cpp) \

# ASM sources
ASM_SOURCES +=  \

# ASM sources
ASMM_SOURCES += \

# C/C++ includes
C_CPP_INCLUDES +=  \
	-I Core/ \
