# C sources
C_SOURCES +=  \
	$(wildcard Driver/*.c) \

# CPP sources
CPP_SOURCES +=  \

# ASM sources
ASM_SOURCES +=  \

# ASM sources
ASMM_SOURCES += \

# C/C++ includes
C_CPP_INCLUDES +=  \
	-I Driver/ \
